"""Export a standalone review document with every original image and audit overlay."""
import base64
import json
from pathlib import Path

audit = json.loads(Path('data/technical_visual_audit.json').read_text())
rows = []
for nid, row in audit['nodes'].items():
    item = dict(row, node_id=nid)
    item['image_data'] = 'data:image/webp;base64,' + base64.b64encode(Path(row['image'].removeprefix('res://')).read_bytes()).decode()
    rows.append(item)
payload = json.dumps(rows, ensure_ascii=False).replace('</', '<\\/')
html = '''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yeti Garage — 90 схем / 376 маркеров</title>
<style>body{margin:0;background:#08121c;color:#e8eff5;font:16px system-ui}main{max-width:1200px;margin:auto;padding:16px}select,button{background:#172735;color:inherit;border:1px solid #4e6478;border-radius:8px;padding:12px;min-height:48px;max-width:100%}select{width:100%}nav{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}#diagram{position:relative;width:100%;background:#fff}#diagram img{display:block;width:100%}.marker{position:absolute;transform:translate(-50%,-50%);border:2px solid #20e7eb;background:#08212c;color:white;border-radius:50%;width:32px;height:32px;min-height:0;padding:0;font-weight:bold;cursor:pointer}.FAIL_MARKER{border-color:#ff716a}.NEEDS_REVIEW{border-color:#ffcd72}.selected{background:#10777d;box-shadow:0 0 0 3px #fff}#detail{padding:14px;border:1px solid #526370;margin:12px 0;border-radius:10px}p{line-height:1.5}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid #354454;overflow-wrap:anywhere}tr{cursor:pointer}small{color:#aab9c5}a{color:#4be2e7}</style>
<main><h1>Полный визуальный аудит</h1><p>CBZB-5node-VALIDATION: исправлены все 5 проблемных узлов двумя batch. 90 схем · 376 маркеров · сохранены 33 прежние правки и добавлены 10 позиций batch. Активных FAIL_ARCHITECTURE: 0. Все пять исправленных узлов — REFERENCE_ONLY. Этот документ показывает обнаруженные несоответствия. Визуальный PASS не подтверждает применимость по VIN. У пяти заменённых схем переключение координат использует только позиции текущего batch, без наложения старых координат на новые пиксели.</p><select id="node"></select><nav><button id="previous">← Предыдущая</button><button id="next">Следующая →</button><button id="coordinates">Координаты: исправленные</button></nav><h2 id="heading"></h2><p id="finding"></p><div id="diagram"></div><div id="detail">Выберите номер или строку.</div><table><thead><tr><th>№</th><th>Деталь</th><th>Результат</th></tr></thead><tbody id="parts"></tbody></table><p id="source"></p></main>
<script>const rows=PAYLOAD;let original=false,selected=null;const byId=id=>document.getElementById(id);const selector=byId('node');rows.forEach((row,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${i+1}/90 · ${row.node_id} · ${row.architecture_status}`;selector.append(option)});function showPart(m){selected=m.number;byId('detail').replaceChildren();const heading=document.createElement('strong');heading.textContent=`№${m.number} · ${m.name_ru} · ${m.visual_status}`;const text=document.createElement('p');text.textContent=m.finding_ru;const status=document.createElement('small');status.textContent=m.documentary_status;byId('detail').append(heading,text,status);document.querySelectorAll('.marker').forEach(b=>b.classList.toggle('selected',Number(b.dataset.number)===selected))}function render(){const row=rows[Number(selector.value)];selected=null;byId('heading').textContent=row.node_id;byId('finding').textContent=`${row.architecture_status}: ${row.finding_ru}`;const diagram=byId('diagram');diagram.replaceChildren();const image=document.createElement('img');image.src=row.image_data;image.alt=row.node_id;diagram.append(image);const parts=byId('parts');parts.replaceChildren();row.markers.forEach(m=>{const xy=!original&&m.corrected_xy?m.corrected_xy:[m.x,m.y];const marker=document.createElement('button');marker.className='marker '+m.visual_status;marker.dataset.number=m.number;marker.textContent=String(Number(m.number));marker.style.left=(xy[0]*100)+'%';marker.style.top=(xy[1]*100)+'%';marker.title=m.name_ru;marker.onclick=()=>showPart(m);diagram.append(marker);const tr=document.createElement('tr');[String(Number(m.number)),m.name_ru,m.visual_status].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});tr.onclick=()=>showPart(m);parts.append(tr)});byId('detail').textContent='Выберите номер или строку.';const link=document.createElement('a');link.href=row.source.url;link.textContent=row.source.title;link.target='_blank';link.rel='noopener';byId('source').replaceChildren(link);byId('coordinates').textContent='Координаты: '+(original?'исходные':'исправленные')}selector.onchange=render;byId('previous').onclick=()=>{selector.value=Math.max(0,Number(selector.value)-1);render()};byId('next').onclick=()=>{selector.value=Math.min(rows.length-1,Number(selector.value)+1);render()};byId('coordinates').onclick=()=>{original=!original;render()};render();</script></html>'''.replace('PAYLOAD',payload)
folder=Path('build/ux');folder.mkdir(parents=True,exist_ok=True);Path('build/.gdignore').write_text('');(folder/'full_marker_visual_audit.html').write_text(html)
print('Standalone audit exported: 90 images / 376 markers')
